baseURL = "http://blog.revolly.com/"
disqusShortname = "revolly"
googleAnalytics = ""
languageCode = "en-us"
theme = "minimal"
title = "Alexei Sitnikov"
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/TheReVolly/"
weight = 3
[[menu.icon]]
name = "github"
url = "https://github.com/revolly/"
weight = 2
[[menu.icon]]
name = "envelope-o"
url = "mailto:revolly@revolly.com"
weight = 1
[[menu.main]]
name = "Projects"
url = "/project/"
weight = 3
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "#64b6e0"
author = "Alexei Sitnikov"
backgroundcolor = "white"
description = "Full-Stack Engineer"
font = "Raleway"
githubusername = "#revolly"
highlight = true
highlightlanguages = ["cs", "javascript", "scss", "css"]
highlightstyle = "solarized-dark"
showborder = true
