baseURL = "http://revolly.com/"
disqusShortname = "revolly"
googleAnalytics = ""
languageCode = "en-us"
theme = "minimal"
title = "Alexei Sitnikov"
[[menu.icon]]
name = "envelope-o"
url = "mailto:revolly@revolly.com"
weight = 1
[[menu.icon]]
name = "github"
url = "https://github.com/revolly/"
weight = 2
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/TheReVolly/"
weight = 3
[[menu.icon]]
name = "telegram-plane"
url = "https://t.me/revolly"
weight = 3
[[menu.main]]
name = "Blog"
url = "/post/"
weight = 2
[[menu.main]]
name = "Open Source"
url = "/project/"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "#64b6e0"
author = "Alexei Sitnikov"
backgroundcolor = "white"
description = "Full-Stack Software Engineer"
font = "Raleway"
githubusername = "revolly"
highlight = true
highlightlanguages = ["cs", "javascript", "scss", "css"]
highlightstyle = "solarized-dark"
profilepic = "/uploads/2018/03/22/photo_2018-03-02_20-32-04.jpg"
showborder = true
